dataset:
  name: 'CloudDataset'
  params:
    idx_fold: 0
    data_dir: 'data'
    csv_filename: 'train_700.ver0.csv'

  splits:
    - mode: 'train'
      split: 'train'
    - mode: 'validation'
      split: 'dev'
    - mode: 'validation'
      split: 'test_dev'
    - mode: 'test'
      split: 'test'


transform:
  name: 'cloud_transform'
  num_preprocessor: 8
  params:
    resize_to: (384, 576)
    crop_size: (384, 576)


model:
  name: 'FPN'
  params:
    num_classes: 4
    encoder: 'resnext101_32x16d_wsl'
    pyramid_channels: 64
    segmentation_channels: 32
    merge: 'cat'


train:
  dir: 'train_dirs/model_b_07'

  batch_size: 8
  sync_bn: True
  gradient_accumulation_step: 1
  num_epochs: 15
  no_bias_decay: True
  encoder_lr_ratio: 0.1


evaluation:
  batch_size: 2


loss:
  name: 'BCEWithLogitsLoss'


optimizer:
  name: 'AdamW'
  params:
    lr: 0.00025
    weight_decay: 0.01


scheduler:
  name: 'OneCycleLR'
  params:
    epochs: 15
    max_lr: [0.00025, 0.00025, 0.000025, 0.000025]
    pct_start: 0.033
    steps_per_epoch: 568


hooks:
  metric:
    name: 'CloudMetricHook'

  loss:
    name: 'CloudLossWeightedHook'
    params:
      seg_loss_names: ['BCEWithLogitsLoss', 'DiceLoss']
      seg_weights: [0.75,0.25]
      ignore_negative: True

  post_forward:
    name: 'CloudPostForwardHook'

  write_result:
    name: 'CloudWriteResultHook'
